<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change</name>
   <tag></tag>
   <elementGuidId>f5f43560-2a80-44ae-806f-1485dfbc95ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.a-link-normal.expand-panel-button.celwidget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout-deliveryAddressPanel']/div/div[2]/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Change delivery address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25e1050f-7eef-41a9-bd15-e263ece82cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-args</name>
      <type>Main</type>
      <value>redirectReason=shipaddressselectChangeClicked</value>
      <webElementGuid>9d8498ef-a407-4b1c-971a-c466270ef3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>checkout-change-shipaddressselect</value>
      <webElementGuid>b085b34d-b983-4aa6-920c-e357cff46405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>c51e6edd-e6c6-45dc-bef9-79664fad0ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frompage</name>
      <type>Main</type>
      <value>payselect</value>
      <webElementGuid>797eef48-af9e-45bc-855d-954cd068d7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reftag</name>
      <type>Main</type>
      <value>chk_payselect_chg_shipaddressselect</value>
      <webElementGuid>26be0c44-8c8a-4bca-a909-65f169d91631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-topage</name>
      <type>Main</type>
      <value>shipaddressselect</value>
      <webElementGuid>cdee2a6c-a8dc-4a92-a928-cedc564526d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/checkout/p/p-404-2033450-6643532/address?pipelineType=Chewbacca&amp;isBuyNow=1&amp;referrer=pay&amp;ref_=chk_payselect_chg_shipaddressselect</value>
      <webElementGuid>8c4167ba-17d1-48f5-9c3c-f06e62322849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Change delivery address</value>
      <webElementGuid>2ec5571a-b560-4c1b-b9d0-2cffb23ac433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal expand-panel-button celwidget</value>
      <webElementGuid>b3dad6f2-1c81-48e9-9c62-c663ddbd196a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/checkout/p/p-404-2033450-6643532/address?pipelineType=Chewbacca&amp;isBuyNow=1&amp;referrer=pay&amp;ref_=chk_payselect_chg_shipaddressselect</value>
      <webElementGuid>a02aa593-e90e-4b98-b689-fb1c711e60ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>iq3xd7-to7vts-wn18ot-r6mhum</value>
      <webElementGuid>8c3b725e-9f9f-4d1a-9dd2-7a5cd372dd87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            Change
                                                        </value>
      <webElementGuid>98c9a538-0726-4ea1-94e3-81301d0c7263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-deliveryAddressPanel&quot;)/div[@class=&quot;a-row&quot;]/div[@class=&quot;a-column a-span4 a-text-right a-spacing-base a-span-last&quot;]/span[@class=&quot;a-declarative&quot;]/a[@class=&quot;a-link-normal expand-panel-button celwidget&quot;]</value>
      <webElementGuid>0175eb94-f9d6-4753-896f-55c7317f0e5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-deliveryAddressPanel']/div/div[2]/span/a</value>
      <webElementGuid>d79a2bf0-4b23-46b7-b89b-71495653877d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Change')]</value>
      <webElementGuid>d26f9c14-309c-4768-b59c-646402b0b63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivering to Rahul Chauhan'])[1]/following::a[2]</value>
      <webElementGuid>df79f7c4-46aa-48bd-884a-a67365509e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading your address information...'])[1]/following::a[3]</value>
      <webElementGuid>96a398e7-12ee-407a-bbe8-198069c10c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment method'])[1]/preceding::a[1]</value>
      <webElementGuid>9d52ac19-993c-4ec7-be6d-0fe3b1e2a298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting your payment method...'])[1]/preceding::a[1]</value>
      <webElementGuid>8d82f7da-511a-47b7-8248-3ccc323268f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Change']/parent::*</value>
      <webElementGuid>1d7a6e79-39b7-4568-95bb-a7031b7bb643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/checkout/p/p-404-2033450-6643532/address?pipelineType=Chewbacca&amp;isBuyNow=1&amp;referrer=pay&amp;ref_=chk_payselect_chg_shipaddressselect')]</value>
      <webElementGuid>3d4b33dd-0947-402a-882e-3d5e6ddcb888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/span/a</value>
      <webElementGuid>5363e424-edca-4478-a239-4efd69ddcfa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/checkout/p/p-404-2033450-6643532/address?pipelineType=Chewbacca&amp;isBuyNow=1&amp;referrer=pay&amp;ref_=chk_payselect_chg_shipaddressselect' and (text() = '
                                                            Change
                                                        ' or . = '
                                                            Change
                                                        ')]</value>
      <webElementGuid>cfb12368-1040-429c-a987-7597b31fc0e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
