<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change_1</name>
   <tag></tag>
   <elementGuidId>f794e491-3ab6-4417-9617-fe42ff86a69d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkout-paymentOptionPanel > div.a-row > div.a-column.a-span4.a-text-right.a-spacing-base.a-span-last > span.a-declarative > a.a-link-normal.expand-panel-button.celwidget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout-paymentOptionPanel']/div/div[2]/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Change payment method&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc89bfcd-c704-4e74-a6e8-ddd0e71e5432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-args</name>
      <type>Main</type>
      <value>redirectReason=payselectChangeClicked</value>
      <webElementGuid>ff42f42b-25e5-4a1a-bcd8-00ea786bf33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>checkout-change-payselect</value>
      <webElementGuid>6e8309a5-88ff-4279-84be-af8e281f27c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>6fbc25fe-854a-4e26-81ff-947ee7ced72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frompage</name>
      <type>Main</type>
      <value>offers</value>
      <webElementGuid>98c7bed6-ba69-462e-8e55-0179d333d301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-reftag</name>
      <type>Main</type>
      <value>chk_offers_chg_payselect</value>
      <webElementGuid>240e5b9d-912b-40f4-a873-3f01e1fbcc88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-topage</name>
      <type>Main</type>
      <value>payselect</value>
      <webElementGuid>460c8bb8-1742-4758-b770-f6c2f9068bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/checkout/p/p-404-2033450-6643532/pay?pipelineType=Chewbacca&amp;isBuyNow=1&amp;referrer=offers&amp;ref_=chk_offers_chg_payselect</value>
      <webElementGuid>e14c9ef7-1eee-4806-9bc5-95f3279458a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Change payment method</value>
      <webElementGuid>bf42bb12-684f-4ae3-a60d-435a5c45de97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal expand-panel-button celwidget</value>
      <webElementGuid>c5a40833-1fe3-46b9-af3d-f3cd6820c758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/checkout/p/p-404-2033450-6643532/pay?pipelineType=Chewbacca&amp;isBuyNow=1&amp;referrer=offers&amp;ref_=chk_offers_chg_payselect</value>
      <webElementGuid>d809b552-ade0-454a-9b94-3b1ae7e71439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>gnrmp2-2836jd-xprlr3-to76zl</value>
      <webElementGuid>80586363-4366-4635-9c7b-a91049c2aa3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            Change
                                                        </value>
      <webElementGuid>f0a893b1-7f5f-47d3-93cb-c649786dad7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-paymentOptionPanel&quot;)/div[@class=&quot;a-row&quot;]/div[@class=&quot;a-column a-span4 a-text-right a-spacing-base a-span-last&quot;]/span[@class=&quot;a-declarative&quot;]/a[@class=&quot;a-link-normal expand-panel-button celwidget&quot;]</value>
      <webElementGuid>d3c4ae0a-6ff6-4cd8-a798-d19f2a740bb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-paymentOptionPanel']/div/div[2]/span/a</value>
      <webElementGuid>e7d5f350-7905-4b35-9f74-9d3ee29f07b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Change')])[2]</value>
      <webElementGuid>328051a6-ac92-482d-a10f-4441cfd9dd8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use a gift card, voucher or promo code'])[1]/following::a[1]</value>
      <webElementGuid>698f474a-ee26-4da3-a600-b3d89788bb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay on delivery (Cash/Card)'])[1]/following::a[2]</value>
      <webElementGuid>a64cd304-6abf-4a6a-84f1-38f29ce13013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offers'])[1]/preceding::a[1]</value>
      <webElementGuid>4e475bd6-0986-4e6b-b1a7-58c8cf5d3255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saving your settings...'])[1]/preceding::a[1]</value>
      <webElementGuid>9da121f1-b91f-4959-9455-34d91c393780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/checkout/p/p-404-2033450-6643532/pay?pipelineType=Chewbacca&amp;isBuyNow=1&amp;referrer=offers&amp;ref_=chk_offers_chg_payselect')]</value>
      <webElementGuid>9af7d09b-89ee-447b-830a-281de1bf7d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div[2]/span/a</value>
      <webElementGuid>9aba4ebb-42af-4f16-aa16-dcacc8daf863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/checkout/p/p-404-2033450-6643532/pay?pipelineType=Chewbacca&amp;isBuyNow=1&amp;referrer=offers&amp;ref_=chk_offers_chg_payselect' and (text() = '
                                                            Change
                                                        ' or . = '
                                                            Change
                                                        ')]</value>
      <webElementGuid>fab6fc91-f94f-4338-a884-08377c15bd8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
