<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add gift options_placeYourOrder1</name>
   <tag></tag>
   <elementGuidId>adcefe1b-8423-4e37-be42-44481b940b4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bottomSubmitOrderButtonId > span.a-button-inner > #placeOrder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='placeOrder'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#bottomSubmitOrderButtonId [data-testid=&quot;SPC_selectPlaceOrder&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8260106b-6d42-4773-a933-14961e938269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>placeOrder</value>
      <webElementGuid>26e9c61a-9eb9-49e3-9380-69a74b1b09fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>placeYourOrder1</value>
      <webElementGuid>2970fb91-5d58-4166-861b-5dd363c39793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Place your order</value>
      <webElementGuid>98c5599f-546d-4159-9714-194edda6e888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-client-component</name>
      <type>Main</type>
      <value>PlaceYourOrder</value>
      <webElementGuid>30c6fea9-b8a0-47a0-a58a-7481f543ff13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>checkout-place-your-order-button</value>
      <webElementGuid>c649ce3d-d512-482e-8bbf-23f3b6b2a438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>ef7b807c-40db-4ef8-8884-3ab612c26d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disable-pipelining</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>883585cc-1079-483f-a2ad-6edb44e05f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>SPC_selectPlaceOrder</value>
      <webElementGuid>e886a24a-853d-4a88-b951-967ba653ab9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input place-your-order-button</value>
      <webElementGuid>55aeaa47-0381-4a7f-8424-2fc9631d54c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>39010eb3-a424-4a18-a553-4229357f4128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Place your order</value>
      <webElementGuid>7784b81b-39d5-4d86-aa1a-5c5ae49ddb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>bottomSubmitOrderButtonId-announce</value>
      <webElementGuid>2883a77d-7730-4119-8554-d44501895ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>z5sls7-3ar4r6-w0a1vv-i1s3al</value>
      <webElementGuid>edd5ebf8-222f-4d96-b876-7403b5356a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bottomSubmitOrderButtonId&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@id=&quot;placeOrder&quot;]</value>
      <webElementGuid>b31481ca-5c6b-441e-b552-596e487653fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='placeOrder'])[3]</value>
      <webElementGuid>e3fbe58f-11dd-4c86-8bdd-34c8ae42b236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='bottomSubmitOrderButtonId']/span/input</value>
      <webElementGuid>3b022db9-d49a-4f0d-b565-b603718a6bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span/input</value>
      <webElementGuid>9f7036df-19f2-44ef-9523-4949c0273a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'placeOrder' and @name = 'placeYourOrder1' and @title = 'Place your order' and @type = 'submit']</value>
      <webElementGuid>cf937dfd-a5c4-4778-96f9-ee3d3ab520d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
