<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__a-button-input</name>
   <tag></tag>
   <elementGuidId>af03a4ef-fd35-4142-a6f7-761581ad72eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkout-primary-continue-button-id > span.a-button-inner > input.a-button-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;bottom-continue-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb100cd1-3031-4f8b-b8ef-f0e147de638a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-purchase-id</name>
      <type>Main</type>
      <value>404-2033450-6643532</value>
      <webElementGuid>9b2a592a-eda9-4076-828e-7fe793994aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>checkout-primary-continue-shipaddressselect</value>
      <webElementGuid>11035ae6-86b1-42a1-82d6-b2e404aeaf36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2443957e-6d0b-4785-bc9a-c2c1d2487837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>bottom-continue-button</value>
      <webElementGuid>5a20145b-996f-4d89-b4cb-1f2a26cd4fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>ea2396fd-c5f1-41dc-bd8b-7ee53a2e4800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6da6eac6-70ff-4ca9-b062-bc6036a86a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>checkout-primary-continue-button-id-announce</value>
      <webElementGuid>fc614186-9420-4ef2-8657-3ea045ca1f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>kh5puf-16mfjw-ay2yja-ia99s4</value>
      <webElementGuid>280e8340-8d2b-4cf2-8335-b7e2f7552b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-primary-continue-button-id&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>87bc66ef-c4e7-4566-be47-2bed6c5904f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='submit'])[2]</value>
      <webElementGuid>74b4e1f2-58d6-4a3b-b776-c7cebf8fb145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='checkout-primary-continue-button-id']/span/input</value>
      <webElementGuid>f00d7816-5392-420c-82da-f55bb3a34c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/span/span/input</value>
      <webElementGuid>66c44590-b31b-48ed-b24c-bcdc9bc00782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>776e4517-4cc5-4cda-8992-29854b5f191a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
