<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose an Option_ppw-instrumentRowSelection</name>
   <tag></tag>
   <elementGuidId>3facff46-bb34-4b6a-a830-15aced6e9435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-TT8gJn-129</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-TT8gJn-129']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Other UPI Apps&quot;i >> internal:label=&quot;&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f95649c0-07c5-47b8-8a51-3b909eebc8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-TT8gJn-129</value>
      <webElementGuid>fc73d0dc-491e-41c0-87ed-6ce95c03f023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>205d932b-f4de-4e3f-8f61-76d8ab2a557a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>a989f2ab-a9e5-4cb5-91e4-81355ec23846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>instrumentId=amzn1.pm.poa.YW16bjEucG9hOmFtem4xLnBvYS5wb2RhLlVuaWZpZWRQYXltZW50c0ludGVyZmFjZTox.QTIzSVNZUTE1VE4xWE4&amp;isExpired=false&amp;paymentMethod=UnifiedPaymentsInterface&amp;tfxEligible=false</value>
      <webElementGuid>703f5ca4-9365-4763-865e-130ea89da3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-TT8gJn-129&quot;)</value>
      <webElementGuid>afa16cb0-116f-4bec-9b2e-a7f8a1107954</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-TT8gJn-129']</value>
      <webElementGuid>131e3a84-feeb-4d3e-8597-433086d26cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-TT8gJn-128']/div/div/div/div/div/div/label/input</value>
      <webElementGuid>d6f96dd5-9c39-46ec-a10d-9a2fa1835700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/label/input</value>
      <webElementGuid>49608ab8-b4b2-4255-ad9d-93c1e2a49b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-TT8gJn-129' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>5216ed64-3620-4258-ae9d-b27231118b32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
