<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Why_ppw-instrumentRowSelection</name>
   <tag></tag>
   <elementGuidId>0ab0e026-cb2e-404d-af0c-df8453debb6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-TT8gJn-139</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-TT8gJn-139']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cash on Delivery/Pay on Delivery&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6df0ddd5-733c-4f7c-b2dc-ba66c0698a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-TT8gJn-139</value>
      <webElementGuid>6f7a0820-e6b9-45c4-8e0c-47707c930dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2f60cda0-c495-4ef9-8da7-6fc29ed15a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>66057af3-daef-4350-9b01-fc4e10f1908b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>instrumentId=0h_PE_CUS_18b1c868-2e63-40e2-8b24-414fe05d88c8%2FCash&amp;isExpired=false&amp;paymentMethod=COD&amp;tfxEligible=false</value>
      <webElementGuid>b2dfa85a-acb3-4181-9060-f71119d15cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-TT8gJn-139&quot;)</value>
      <webElementGuid>5b6ad24e-a865-4045-98ea-f9c6eb9ccf4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-TT8gJn-139']</value>
      <webElementGuid>ca882972-d77c-4650-9f31-3834c66f209b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-TT8gJn-138']/div/div/div/div/div/div/label/input</value>
      <webElementGuid>a4582901-d43f-40ef-8e33-2c39eb5a7335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/label/input</value>
      <webElementGuid>d0ff2e2b-fd70-4a17-bbdf-c62132e2fdc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-TT8gJn-139' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>18583154-4dd7-412d-b361-45ae1ba1a14a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
