<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amazon accepts all major credit   car_451b00</name>
   <tag></tag>
   <elementGuidId>5c8345d1-b68a-4213-a932-38f8c5114bb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-3gdaR4-109</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-3gdaR4-109']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Net Banking&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6261baa5-d66e-45ed-bd60-0a11dba3b446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-3gdaR4-109</value>
      <webElementGuid>707b96cb-aefe-4356-a472-fbb5baa5ee34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>dc092b25-d390-4ba9-98ab-629408f6cc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>6aba5a76-ca1d-40b5-9b4a-c81d75398e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>instrumentId=NetBanking&amp;isExpired=false&amp;paymentMethod=NB&amp;tfxEligible=false</value>
      <webElementGuid>3c9c52df-61f5-418e-a3ca-b4b8157b446b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-3gdaR4-109&quot;)</value>
      <webElementGuid>4f065ec1-d899-40e4-8e25-fc91b6e26066</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-3gdaR4-109']</value>
      <webElementGuid>18ee956b-ccd7-4ab3-b8b8-2c2073a68d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-3gdaR4-108']/div/div/div/div/span/div/label/input</value>
      <webElementGuid>cab57021-246e-4c44-8975-dc98b50ec109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/span/div/label/input</value>
      <webElementGuid>48c4dd3b-dc95-4c90-b6e9-dda2e5da3e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-3gdaR4-109' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>81099eb8-c056-46d1-b107-a4dd9d0b6abf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
