<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_The UPI ID is in the format of nameph_029c41</name>
   <tag></tag>
   <elementGuidId>034c83a7-5149-47e9-bed7-698e60bfc7a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-3gdaR4-134</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-3gdaR4-134']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;EMI&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d71cc98-e60c-48c9-b1b7-a7f308563591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-3gdaR4-134</value>
      <webElementGuid>2a05a2f9-0f0a-43d6-b221-199039007b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6b99edd7-6424-401e-bc96-f1fe7c1ab383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>6f1b91b3-1f56-4360-a781-f2d1242265c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>instrumentId=EMI&amp;isExpired=false&amp;paymentMethod=CC&amp;tfxEligible=false</value>
      <webElementGuid>c5b531b4-087e-4134-9a46-5270a98a10cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-3gdaR4-134&quot;)</value>
      <webElementGuid>d6971648-8eab-4ae5-b0ee-4cbf79fe09f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-3gdaR4-134']</value>
      <webElementGuid>f7b9bbd9-1886-41db-86d5-d6ad30999ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-3gdaR4-133']/div/div/div/div/span/div/label/input</value>
      <webElementGuid>1e5b9af6-126b-4263-9d7a-436c9c4117d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/span/div/label/input</value>
      <webElementGuid>8c686666-be2d-4803-ab0a-150d8bc03faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-3gdaR4-134' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>0dbe0b9f-9ffc-4a56-8b47-285e60ead258</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
