<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Another payment method_ppw-instrument_d02253</name>
   <tag></tag>
   <elementGuidId>125d0f24-2761-4751-9af6-5c1238ebc5c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-3gdaR4-103</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-3gdaR4-103']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;&quot;s >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>543688b6-9830-4c6e-9c11-9c9f0dd89232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-3gdaR4-103</value>
      <webElementGuid>b51010a9-85ee-4c49-b977-538ac0bed0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5fa9f44d-2475-4be7-b5df-18fc7f9c43d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>da6676fe-59e1-416d-b463-a295b9f81b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SelectableAddCreditCard</value>
      <webElementGuid>b8fa183c-6fe9-4ecd-b308-57335d60a8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-3gdaR4-103&quot;)</value>
      <webElementGuid>7b133702-be44-49ac-8e46-4a0c2a55a9a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-3gdaR4-103']</value>
      <webElementGuid>8fd15a21-2dc1-47da-9985-ca62642e77c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-3gdaR4-102']/div/div/div/div/div/span/div/label/input</value>
      <webElementGuid>7122b349-aaef-4595-9ff8-cc3f51fbd265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>86eff386-8f23-4039-9035-7c932c64ab63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-3gdaR4-103' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>f96dde89-689c-4c2d-b9e8-c6ad9b276178</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
