<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Why_ppw-instrumentRowSelection</name>
   <tag></tag>
   <elementGuidId>e8ed205a-0069-435d-b254-a8563ddde795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-3gdaR4-147</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-3gdaR4-147']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cash on Delivery/Pay on Delivery&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79fb2017-a0b5-43ba-ae7b-bb75a8ff8526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-3gdaR4-147</value>
      <webElementGuid>8073fa22-dcc3-4562-90d8-0e2fd46e7dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a9121550-bbda-4f5d-a34f-273403e42790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>34b0333f-3f09-4380-b57a-7454f6e51d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>instrumentId=0h_PE_CUS_18b1c868-2e63-40e2-8b24-414fe05d88c8%2FCash&amp;isExpired=false&amp;paymentMethod=COD&amp;tfxEligible=false</value>
      <webElementGuid>ab630bbe-f48a-470e-99d7-6a15379702cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-3gdaR4-147&quot;)</value>
      <webElementGuid>3fe29366-0873-468e-a28c-aa8fb9048e6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-3gdaR4-147']</value>
      <webElementGuid>5942b790-dd43-4db1-8f2b-df83ebaca8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-3gdaR4-146']/div/div/div/div/div/div/label/input</value>
      <webElementGuid>81049464-db94-4c85-b13a-8c0439f47952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div/label/input</value>
      <webElementGuid>26595c5f-5e9c-46cd-9a45-d8bb41cf227a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-3gdaR4-147' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>be041b62-044f-463c-a67b-fb0a1deb4e3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
