<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose an Option_ppw-instrumentRowSelection</name>
   <tag></tag>
   <elementGuidId>44859fa3-510b-4ef0-b16e-cf995d015e02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pp-3gdaR4-129</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pp-3gdaR4-129']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Other UPI Apps&quot;i >> internal:label=&quot;&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>151f5cea-f795-4624-a612-4f598e27b15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pp-3gdaR4-129</value>
      <webElementGuid>e106d936-5bf8-4036-83d7-466d6ab9fe46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>115e5c00-dbc8-4ae8-9af7-8a688bf32457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ppw-instrumentRowSelection</value>
      <webElementGuid>1d029833-7d38-429f-bb9d-6bc0433c1bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>instrumentId=amzn1.pm.poa.YW16bjEucG9hOmFtem4xLnBvYS5wb2RhLlVuaWZpZWRQYXltZW50c0ludGVyZmFjZTox.QTIzSVNZUTE1VE4xWE4&amp;isExpired=false&amp;paymentMethod=UnifiedPaymentsInterface&amp;tfxEligible=false</value>
      <webElementGuid>c111a3e1-db95-4821-8766-6207f0aa0cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pp-3gdaR4-129&quot;)</value>
      <webElementGuid>6997429a-6de2-4866-8b1d-4d6bedec146c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pp-3gdaR4-129']</value>
      <webElementGuid>e7939365-3bfd-41d1-85a5-546b1f86c460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pp-3gdaR4-128']/div/div/div/div/div/div/label/input</value>
      <webElementGuid>31762c08-8862-44ae-bcb2-8be1738b7027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/label/input</value>
      <webElementGuid>2dabe209-23c9-49c5-84ad-f6dc7f032eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'pp-3gdaR4-129' and @type = 'radio' and @name = 'ppw-instrumentRowSelection']</value>
      <webElementGuid>f2b892a1-2435-4e93-b92c-177e06df4f6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
