<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please wait  32  seconds before reque_171295</name>
   <tag></tag>
   <elementGuidId>53081f56-f0d2-4f4d-8793-cf3bf3239739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cvf-submit-otp-button > span.a-button-inner > input.a-button-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Submit code&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>330937d8-ee54-441b-869a-8877e2958fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>63605bca-e655-4804-b4c0-20ce4add68c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2c61d32f-6709-44e8-9c62-b3acfd4ab787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>cvf-submit-otp-button-announce</value>
      <webElementGuid>c865bad8-e8cf-40da-8117-66376a8f5f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cvf-submit-otp-button&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>32daa52a-18f2-4498-9fc9-78aa1c069870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='submit'])[2]</value>
      <webElementGuid>91acfaa4-7918-4a7f-bebc-be38ab30ffa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cvf-submit-otp-button']/span/input</value>
      <webElementGuid>f50a3f02-7273-4838-87ab-6eed6d3e4950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/span/span/input</value>
      <webElementGuid>6fc0e3a6-543e-4e71-b04c-6234ee56fcb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>fe05f8ff-9262-48b8-bb6d-3d4bdcca07d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
