<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Passkey error_a-button-input</name>
   <tag></tag>
   <elementGuidId>6387bdc6-343c-431f-95ba-042fbee90dbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.a-button-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Continue&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84c60f86-be0b-4266-a3aa-d44975b802ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>ade8485b-43cd-4ebf-8a7c-0da0f8ce338f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f28f4849-3b73-46ec-9c4a-c6b18c8e381e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>continue-announce</value>
      <webElementGuid>edc02919-b2a3-48ed-afa7-9ef8011b5b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continue&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>6bffb540-7a92-4aae-99f8-22d50020c600</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='submit']</value>
      <webElementGuid>aff146a7-3d58-4d8e-a253-50746eeab3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='continue']/span/input</value>
      <webElementGuid>c9d36721-a7d5-4012-8f88-53935372116b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>6e04fc59-4b57-4001-8821-f3e11a813a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>7deecb55-59b2-4192-b1f2-8d619e5df7a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
