<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add to list_keyword</name>
   <tag></tag>
   <elementGuidId>a81d76f5-27e1-4508-8301-12de84c2f6c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add-new-keyword-text-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-new-keyword-text-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#add-new-keyword-text-input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df22d129-f403-4421-a01f-cd03041d622b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0db380cc-d96d-4ca3-8589-7e915afc44d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>4fb77137-3dc2-4aa1-842a-a6712fd6b0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-new-keyword-text-input</value>
      <webElementGuid>07ed9242-0605-4d23-87aa-6808d64a3fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>52948411-0c28-4620-bebe-7b5625ebd56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keyword</value>
      <webElementGuid>4b2bc565-233e-46c2-818e-3ad227715940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-span12</value>
      <webElementGuid>ce73a5f1-2d1b-4e8d-a2a6-48d25cd8ebec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-new-keyword-text-input&quot;)</value>
      <webElementGuid>5565996d-795e-4536-bc02-3323e1110339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add-new-keyword-text-input']</value>
      <webElementGuid>ca3699e2-86e4-4c50-b702-ed6b8ff38e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-new-keyword-form']/span/input</value>
      <webElementGuid>75fde2ba-43e6-4ed2-98b5-76c804e86393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/span/input</value>
      <webElementGuid>fc769bf0-0d05-4a67-8eab-88b463093649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'add-new-keyword-text-input' and @name = 'keyword']</value>
      <webElementGuid>11922c0e-a172-4e99-b2f9-543a859ac196</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
