<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Dopamine detox</name>
   <tag></tag>
   <elementGuidId>b8835482-5c7b-481d-a287-89648fb9d5c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='autocomplete-list-item-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#autocomplete-list-item-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Dopamine detox&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>dc27a888-5a42-4c6e-b94e-e1d4f2afe51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autocomplete-list-item-0</value>
      <webElementGuid>ee2ca01b-25bd-4ef0-9ac1-f0a552c987e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>29703f20-6395-4043-8b68-8ebb2c4c90c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dopamine detox</value>
      <webElementGuid>ac417304-f4ef-4da1-9242-fbdd4f95a859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autocomplete-list-item-0&quot;)</value>
      <webElementGuid>fdc44a7e-9f5c-4041-a7a9-b8edfa968d50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='autocomplete-list-item-0']</value>
      <webElementGuid>445e0a70-ee92-4063-8ef0-3f9a36ab4f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='keyword-autocomplete-list']/li</value>
      <webElementGuid>f3d7bc9d-9e15-4c97-83d4-971819d1ae07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to list'])[1]/following::li[1]</value>
      <webElementGuid>bcf5a939-159f-416a-9eba-ddc033c2fdc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='book'])[1]/preceding::li[1]</value>
      <webElementGuid>9891ea24-345d-4ba4-b595-08847892deac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dopamine detox']/parent::*</value>
      <webElementGuid>9cf1483d-8b5e-46f2-9b96-09a2a5e9f3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/ul/li</value>
      <webElementGuid>a342b794-be06-4f31-8e88-21b8cb045473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'autocomplete-list-item-0' and (text() = 'Dopamine detox' or . = 'Dopamine detox')]</value>
      <webElementGuid>211c760b-935d-4631-a5be-90190e49eda0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
