<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add a note_submit.deleteItem</name>
   <tag></tag>
   <elementGuidId>ef2e4ecf-131d-4036-b73f-85e7b9cb7814</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='submit.deleteItem'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.a-section.a-spacing-none.awl-ul-keyword-item-flex-row > #keyword-action-section-I2SAQVVI52O5X7 > #itemAction_I2SAQVVI52O5X7 > form.a-spacing-none > span.a-declarative > #delete-button-I2SAQVVI52O5X7 > span.a-button-inner > input[name=&quot;submit.deleteItem&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i] >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa1f8f35-fdd5-461f-91bc-ef2d3889d921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.deleteItem</value>
      <webElementGuid>d33adf3d-174f-480a-9ad0-679ed4d467e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-action</name>
      <type>Main</type>
      <value>sab:list_c_wl_lv_ov_lig_d_itemDelete</value>
      <webElementGuid>c08db76e-5252-4308-97c6-bc0bc9a23d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-item-id</name>
      <type>Main</type>
      <value>I2SAQVVI52O5X7</value>
      <webElementGuid>3c2cbaf4-aab2-401d-a9db-d65a8f47b4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>fa538d54-1f2b-4b31-9485-5135902d1b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input a-declarative</value>
      <webElementGuid>dd78ae14-6030-4973-8660-b9dfc68a54b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ef077e77-b8b5-4a19-a9f2-ad2a2a5ef319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>delete-button-I2SAQVVI52O5X7-announce</value>
      <webElementGuid>ff471b79-8936-4de8-b0c2-bd396eac3822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>67h0r-7bgvwn-2mkjx4-ur1cem</value>
      <webElementGuid>3a981f5d-2912-4689-9845-cc6c796e2903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_I2SAQVVI52O5X7&quot;)/div[@class=&quot;a-section a-spacing-none awl-ul-keyword-item-flex-row&quot;]/div[@id=&quot;keyword-action-section-I2SAQVVI52O5X7&quot;]/div[@id=&quot;itemAction_I2SAQVVI52O5X7&quot;]/form[@class=&quot;a-spacing-none&quot;]/span[@class=&quot;a-declarative&quot;]/span[@id=&quot;delete-button-I2SAQVVI52O5X7&quot;]/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input a-declarative&quot;]</value>
      <webElementGuid>697858d8-9d4c-45a2-90ac-dbff17331ade</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='submit.deleteItem'])[2]</value>
      <webElementGuid>108b3565-559b-4586-8fb2-c0dfc2956a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//span[@id='delete-button-I2SAQVVI52O5X7']/span/input)[2]</value>
      <webElementGuid>d30f25ca-725f-4e1d-95bb-ebbbd781c9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/span/span/span/input</value>
      <webElementGuid>1c8f6aec-3549-462c-8fc2-d50ba436d687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submit.deleteItem' and @type = 'submit']</value>
      <webElementGuid>fb19827e-16f8-4f5a-8ba1-ec22776943f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
