<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sell under Amazon Accelerator</name>
   <tag></tag>
   <elementGuidId>dfa2b000-74d9-4702-96f1-a9b1f106d887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navFooter']/div/div/div[5]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Sell under Amazon Accelerator&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14f7c210-ed25-445a-b212-279a3f76d236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://accelerator.amazon.in/?ref_=map_1_b2b_GW_FT</value>
      <webElementGuid>00ca4c41-a97b-4f80-a69a-d6e968fd8ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_a</value>
      <webElementGuid>8ad410e5-03bf-461f-a633-c131db65cb3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sell under Amazon Accelerator</value>
      <webElementGuid>b4556232-ea46-49c2-b734-0a4246f5a279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navFooter&quot;)/div[@class=&quot;navFooterVerticalColumn navAccessibility&quot;]/div[@class=&quot;navFooterVerticalRow navAccessibility&quot;]/div[@class=&quot;navFooterLinkCol navAccessibility&quot;]/ul[1]/li[2]/a[@class=&quot;nav_a&quot;]</value>
      <webElementGuid>ca81c90b-6217-49db-8148-7e91d40644b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div/div/div[5]/ul/li[2]/a</value>
      <webElementGuid>6de2299b-574b-4068-88a5-641508772012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sell under Amazon Accelerator')]</value>
      <webElementGuid>3fbf25ee-6ebb-4216-b7bb-f5bd94feed50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sell on Amazon'])[1]/following::a[1]</value>
      <webElementGuid>8db1cd5e-b4a1-412c-8329-5d52db58c4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make Money with Us'])[1]/following::a[2]</value>
      <webElementGuid>b80d847b-38b7-41e3-8761-7eb67ca9d5c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Protect and Build Your Brand'])[1]/preceding::a[1]</value>
      <webElementGuid>9900882a-3226-47b1-a942-472f25c002bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amazon Global Selling'])[1]/preceding::a[2]</value>
      <webElementGuid>467f5ac9-5a5b-44b7-acbd-3532ec597270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sell under Amazon Accelerator']/parent::*</value>
      <webElementGuid>afb19cc3-b7d7-4d91-94c8-6ed6d789fa4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://accelerator.amazon.in/?ref_=map_1_b2b_GW_FT')]</value>
      <webElementGuid>4d6ce1b9-5d65-427b-a99b-899a72553c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[5]/ul/li[2]/a</value>
      <webElementGuid>f8d6e8ce-9329-49fc-8e16-d1a2f1778ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://accelerator.amazon.in/?ref_=map_1_b2b_GW_FT' and (text() = 'Sell under Amazon Accelerator' or . = 'Sell under Amazon Accelerator')]</value>
      <webElementGuid>200ddb69-6577-4b0d-90f9-143eb051f848</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
