<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Operating system book</name>
   <tag></tag>
   <elementGuidId>685de3cf-ef26-462c-bf9f-c229485fadea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='autocomplete-list-item-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#autocomplete-list-item-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Operating system book&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d5a71eb0-dd4a-4049-9f25-27861a7072c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autocomplete-list-item-1</value>
      <webElementGuid>b60e62d4-5c0e-448f-a596-589161f1d062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>483def6c-f991-4d88-9b2c-450c1899041b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Operating system book</value>
      <webElementGuid>7837762a-dca0-4e11-947c-bf21ebbae0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autocomplete-list-item-1&quot;)</value>
      <webElementGuid>1b033a50-5c0c-43f3-99fc-06ce22c73a2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='autocomplete-list-item-1']</value>
      <webElementGuid>550d207a-5304-401a-b74d-5fd62f868c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='keyword-autocomplete-list']/li[2]</value>
      <webElementGuid>98b10369-1259-405d-99b3-e14bd59d13dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='concepts'])[1]/following::li[1]</value>
      <webElementGuid>045639da-0d1e-41d7-8b5e-f767b27a7d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operating system'])[1]/preceding::li[1]</value>
      <webElementGuid>62e8b4a9-2ee2-4bbb-8690-1a2ed0b8082b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/ul/li[2]</value>
      <webElementGuid>9f18ba28-ff8c-4b77-bd4f-ec1cf75246fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'autocomplete-list-item-1' and (text() = 'Operating system book' or . = 'Operating system book')]</value>
      <webElementGuid>ba0ee1a3-4dd1-454a-90a9-8fca994e0068</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
